"""empty message

Revision ID: 1fca2cab752b
Revises: 0aeb57f68670
Create Date: 2023-06-21 17:30:54.695711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fca2cab752b'
down_revision = '0aeb57f68670'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
