"""empty message

Revision ID: 4183f51d99a6
Revises: cdd8692ee228
Create Date: 2023-06-22 18:09:12.527036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4183f51d99a6'
down_revision = 'cdd8692ee228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
