"""empty message

Revision ID: 5e994da857d5
Revises: 76691bc9f7c5
Create Date: 2023-06-26 16:52:06.375503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e994da857d5'
down_revision = '76691bc9f7c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_ratings', sa.Column('notes', sa.Boolean(), nullable=True))
    op.add_column('day_ratings', sa.Column('mood', sa.Boolean(), nullable=True))
    op.add_column('day_ratings', sa.Column('health', sa.Boolean(), nullable=True))
    op.drop_column('day_ratings', 'notes_rating')
    op.drop_column('day_ratings', 'mood_rating')
    op.drop_column('day_ratings', 'health_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_ratings', sa.Column('health_rating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('day_ratings', sa.Column('mood_rating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('day_ratings', sa.Column('notes_rating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('day_ratings', 'health')
    op.drop_column('day_ratings', 'mood')
    op.drop_column('day_ratings', 'notes')
    # ### end Alembic commands ###
