"""empty message

Revision ID: 7532f1ee7cfd
Revises: f09a51023198
Create Date: 2023-06-23 12:53:53.133268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7532f1ee7cfd'
down_revision = 'f09a51023198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
