"""empty message

Revision ID: 76691bc9f7c5
Revises: e135f39ba0fc
Create Date: 2023-06-26 16:31:03.382844

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '76691bc9f7c5'
down_revision = 'e135f39ba0fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_ratings', sa.Column('health_rating', sa.Boolean(), nullable=True))
    op.drop_column('day_ratings', 'health')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_ratings', sa.Column('health', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('day_ratings', 'health_rating')
    # ### end Alembic commands ###
