"""empty message

Revision ID: cdd8692ee228
Revises: 1fca2cab752b
Create Date: 2023-06-21 17:31:11.907530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd8692ee228'
down_revision = '1fca2cab752b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
